var config = {};

config.webhook = {};
config.capsule = {};

// port   - The port the server is going to listen on. Defaults to 8100.
// secret - Secret key as suggested on the Webhook page which is then simply added as a pathname to the Webhook URL in your MailChimp account and checked for. Nothing too fancy but a small enhancement to security. Leave empty (default setting) if you don't want to use a secret key. Example: If you set the secret to 'ChimpSecret' you need to enter the Webhook URL http://www.yourdomain.com/ChimpSecret in the MailChimp Webhook settings.
// secure - Credentials as generated by the crypto module. If present HTTPS support is enabled for the server. Defaults to false.
config.webhook.port = 8100;
config.webhook.secret = '';
config.webhook.secure = false;

capsule.account = '';
capsule.token = '';

module.exports = config;
