var config = {};

config.webhook = {};
config.mailchimp = {};
config.capsule = {};

// port   - The port the server is going to listen on. Defaults to 8100.
// secret - Secret key as suggested on the Webhook page which is then simply added as a pathname to the Webhook URL in your MailChimp account and checked for. Nothing too fancy but a small enhancement to security. Leave empty (default setting) if you don't want to use a secret key. Example: If you set the secret to 'ChimpSecret' you need to enter the Webhook URL http://www.yourdomain.com/ChimpSecret in the MailChimp Webhook settings.
// secure - Credentials as generated by the crypto module. If present HTTPS support is enabled for the server. Defaults to false.
config.webhook.port = 8100;
config.webhook.secret = '';
config.webhook.secure = false;

config.mailchimp.lists = {
    '7d16b87512': {
        name: 'Test News Alerts list',
        tag: 'Mailchimp news alerts'
    },
    '3b90407bbe': {
        name: 'Test User List',
        tag: 'Mailchimp subscribers'
    }
};

config.capsule.account = '';
config.capsule.token = '';
config.capsule.datatags = {
    'Mailchimp news alerts': [
        'Europe',
        'Americas',
        'Salmon',
        'Latest jobs',
        'Pelagics',
        'Shrimp',
        'Whitefish',
        'Retail & foodservice',
        'Fisheries',
        'Tuna',
        'Aquaculture',
        'People moves',
        'Breaking news',
        'unsubscribed',
        'cleaned'
    ],
    'Mailchimp subscribers': [
        'Premium users',
        'Standard users',
        'Annual users',
        'Monthly users',
        'Group users',
        'Free users',
        'Brussels',
        'Boston',
        'Conxemar',
        'Karen\'s list',
        'unsubscribed',
        'cleaned'
    ]
};

module.exports = config;
