var MailChimpWebhook = require('mailchimp').MailChimpWebhook;

// port   - The port the server is going to listen on. Defaults to 8100.
// secret - Secret key as suggested on the Webhook page which is then simply added as a pathname to the Webhook URL in your MailChimp account and checked for. Nothing too fancy but a small enhancement to security. Leave empty (default setting) if you don't want to use a secret key. Example: If you set the secret to 'ChimpSecret' you need to enter the Webhook URL http://www.yourdomain.com/ChimpSecret in the MailChimp Webhook settings.
// secure - Credentials as generated by the crypto module. If present HTTPS support is enabled for the server. Defaults to false.
var conf = {
    port: 8100,
    secret: 'mailchimp',
    secure: false
};
var webhook = new MailChimpWebhook(conf);

webhook.on('error', function (error) {
    console.log(error.message);
    console.log('error', error);
});

webhook.on('subscribe', function (data, meta) {
    console.log(data.email+' subscribed to your newsletter!');
    console.log('data', data);
    console.log('GROUPINGS', data.merges.GROUPINGS);
    console.log('meta', meta);
});
webhook.on('unsubscribe', function (data, meta) {
    console.log(data.email+' unsubscribed from your newsletter!');
    console.log('data', data);
    console.log('GROUPINGS', data.merges.GROUPINGS);
    console.log('meta', meta);
});

webhook.on('profile', function (data, meta) {
    console.log(data.email+' updated his profile!');
    console.log('data', data);
    console.log('GROUPINGS', data.merges.GROUPINGS);
    console.log('meta', meta);
});
webhook.on('upemail', function (data, meta) {
    console.log(data.email+' updated his email address!');
    console.log('data', data);
    console.log('meta', meta);
});
webhook.on('cleaned', function (data, meta) {
    console.log(data.email+' has been cleaned from your newsletter!');
    console.log('data', data);
    console.log('GROUPINGS', data.merges.GROUPINGS);
    console.log('meta', meta);
});

webhook.on('campaign', function (data, meta) {
    console.log('status of campaign "' + data.subject + '" has been changed!');
    console.log('data', data);
    console.log('meta', meta);
});
